version: "3.8"

services:
  # MySQL Database (Development)
  mysql:
    image: mysql:8.0
    container_name: mailman-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - mailman-dev-network

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mailman-backend-dev
    restart: unless-stopped
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mailman-dev-network
    volumes:
      - ./backend:/app
      - go_modules:/go/pkg/mod
    command: go run ./cmd/mailman

  # Frontend (Development with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mailman-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mailman-dev-network
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  mailman-dev-network:
    driver: bridge

volumes:
  mysql_dev_data:
    driver: local
  go_modules:
    driver: local
